export function kickoutToLogin(message: string) {
  switch (message) {
    case "A_DEMONSTRATION_REQUEST_MUST_CONTAIN_AT_LEAST_ONE_ACHIEVEMENT":
    case "ACHIEVEMENT_NOT_FOUND":
    case "CURRENT_USER_NOT_IN_SUBMITTERS":
    case "DEMONSTRATION_NOT_FOUND":
    case "HELPREQUEST_EXPIRED":
    case "HELPREQUEST_NOT_FOUND":
    case "HELPREQUEST_NOT_PICKED_UP":
    case "STUDENTS_MAY_NOT_CLAIM_DEMONSTRATION":
    case "DEMONSTRATION_DONE_DOES_NOT_MATCH_REQUEST":
    case "DEMONSTRATION_ALREADY_GRADED":
    case "HELPREQUEST_CANNOT_MARK_BY_STUDENT_NOT_IN_HELPREQUEST":
    case "STUDENTS_MAY_NOT_CLAIM_OR_UNCLAIM_DEMONSTRATION":
    case "STUDENT_NOT_ALLOWED_TO_PERFORM_THAT_ACTION":
    case "DEMONSTRATION_CONTAINED_NON_DEMONSTRATABLE_ACHIEVEMENT":
    case "CSV_MALFORMED":
    case "CSV_CONTAINS_MORE_THAN_A_SINGLE_LINE":
    case "INSUFFICIENT_PRIVILEGES":
    case "USER_ALREADY_EXISTS":
    case "USER_MALFORMED_ROLE":
    case "USER_MISSING_ROLE":
    case "USER_LAST_NAME_SHORT":
    case "USER_FIRST_NAME_SHORT":
    case "USER_EDIT_OTHER_USER":
    case "USER_NOT_CURRENTLY_ENROLLED":
    case "USER_NOT_FOUND":
    case "USER_IN_MULTIPLE_HELP_REQUEST":
    case "GRADING_REQUIRES_VERIFIED_PROFILE_PIC":
      return false;

    default:
      return true;
  }
}
